#!/bin/sh

Yes="Y"
mac=""

if [ "$#" -eq 0 ]; then
    echo "Set as default d0:d0:d0:0d:0d:0d (Y/N) ?"
    read Yes
    if [ "$Yes" = "Y" ] || [ "$Yes" = "y" ] || [ "$Yes" = "YES" ] || [ "$Yes" = "yes" ] || [ -z "$Yes" ]; then
        mac="d0:d0:d0:0d:0d:0d"
    else
        exit 1
    fi
fi

if [ "$#" -eq 1 ]; then
mac="$1"
fi

if [ "$#" -gt 1 ]; then
    echo "Usage: $0 <new_mac_address>"
    echo "example: $0 d0:d0:d0:0d:0d:0d"
    exit 1
fi

echo "Changing MAC address of eth0 to $mac"
ifconfig eth0 down
ifconfig eth0 hw ether "$mac"
ifconfig eth0 up
